# Generated by Django 5.2 on 2025-04-14 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('exam', 'Exam'), ('test_work', 'Test Work'), ('school_meeting', 'School meeting'), ('parent_meeting', 'Parent meeting'), ('personal_meeting', 'Personal meeting')], max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=255)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(blank=True, related_name='events', to='tasks.task')),
            ],
        ),
    ]
