# Generated by Django 5.2 on 2025-05-09 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='events.eventcomment'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='response',
            field=models.CharField(choices=[('unanswered', 'Unanswered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('leaved', 'Leaved')], default='unanswered', max_length=10),
        ),
    ]
