# Generated by Django 5.2 on 2025-04-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('test_work', 'Test Work'), ('school_meeting', 'School Meeting'), ('parent_meeting', 'Parent Meeting'), ('personal_meeting', 'Personal Meeting')], max_length=50),
        ),
    ]
